# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-sls-api-services
frameworkVersion: "1.54.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: aws-deploy
  region: us-east-1


functions:
  app-api-sls:
    handler: handler.handler
    events:
     - http:
         path: /
         method: get
         cors: true
     - http:
         path: /{proxy+}
         method: any
         cors: true